name: on pr and push
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
run-name: pr Checks
jobs:
  Check-Arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2.0.0
        with:
          library-manager: false
          compliance: strict
          project-type: sketch
          path: ./Arduino device code/lock_box/
      - uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: arduino:megaavr:uno2018
          libraries: |
            - name: FastLED
            - name: WiFiNINA
            - name: ArduinoECCX08
            - name: crypto
              local-path: ./Arduino device code/libraries/crypto
          sketch-paths: Arduino device code
  Check_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm install -g eas-cli
      - name: Change wrapper permissions
        run: cd android && chmod +x ./gradlew
      - run: npm run build
